In [8]:

import pandas as pd
import numpy as np
import joblib

# Sklearn utilities
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, r2_score

# Classification Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# Regression Models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

# Datasets (Inbuilt - Internet connection error )
from sklearn.datasets import load_breast_cancer, load_diabetes


In [4]:
# Q1. DATASET SELECTION & PREPROCESSING

print("--- Step 1: Loading & Preprocessing Data ---")

# 1. Classification (Breast Cancer)
data_clf = load_breast_cancer()
df_clf = pd.DataFrame(data_clf.data, columns=data_clf.feature_names)
df_clf['target'] = data_clf.target

X_clf = df_clf.drop(columns=['target'])
y_clf = df_clf['target']

X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
    X_clf, y_clf, test_size=0.2, random_state=42
)

scaler_clf = StandardScaler()
X_train_clf_scaled = scaler_clf.fit_transform(X_train_clf)
X_test_clf_scaled = scaler_clf.transform(X_test_clf)


# 2. Regression (Diabetes)
data_reg = load_diabetes()
df_reg = pd.DataFrame(data_reg.data, columns=data_reg.feature_names)
df_reg['target'] = data_reg.target

X_reg = df_reg.drop(columns=['target'])
y_reg = df_reg['target']

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

scaler_reg = StandardScaler()
X_train_reg_scaled = scaler_reg.fit_transform(X_train_reg)
X_test_reg_scaled = scaler_reg.transform(X_test_reg)

print("Data Preprocessing Completed Successfully!\n")


--- Step 1: Loading & Preprocessing Data ---
Data Preprocessing Completed Successfully!



In [5]:
# Q2. CLASSIFICATION ALGORITHMS

print("--- Step 2: Training Classification Models ---")

clf_models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Support Vector Machine": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}

clf_results = []
trained_clf_models = {}

for name, model in clf_models.items():
    model.fit(X_train_clf_scaled, y_train_clf)
    y_pred = model.predict(X_test_clf_scaled)
    acc = accuracy_score(y_test_clf, y_pred)

    trained_clf_models[name] = model
    clf_results.append({"Model": name, "Accuracy": acc})

    print(f"\n--- {name} ---")
    print(f"Accuracy: {acc:.4f}")
    print("Confusion Matrix:\n", confusion_matrix(y_test_clf, y_pred))

clf_df = pd.DataFrame(clf_results).sort_values(by="Accuracy", ascending=False)
print("\nClassification Models Comparison:\n", clf_df.to_string(index=False))



--- Step 2: Training Classification Models ---

--- Logistic Regression ---
Accuracy: 0.9737
Confusion Matrix:
 [[41  2]
 [ 1 70]]

--- Decision Tree ---
Accuracy: 0.9474
Confusion Matrix:
 [[40  3]
 [ 3 68]]

--- Support Vector Machine ---
Accuracy: 0.9825
Confusion Matrix:
 [[41  2]
 [ 0 71]]

--- K-Nearest Neighbors ---
Accuracy: 0.9474
Confusion Matrix:
 [[40  3]
 [ 3 68]]

--- Naive Bayes ---
Accuracy: 0.9649
Confusion Matrix:
 [[40  3]
 [ 1 70]]

Classification Models Comparison:
                  Model  Accuracy
Support Vector Machine  0.982456
   Logistic Regression  0.973684
           Naive Bayes  0.964912
         Decision Tree  0.947368
   K-Nearest Neighbors  0.947368


In [6]:
# Q3. REGRESSION ALGORITHMS

print("\n--- Step 3: Training Regression Models ---")

reg_models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree Regressor": DecisionTreeRegressor(random_state=42),
    "Support Vector Regressor": SVR(),
    "KNN Regressor": KNeighborsRegressor()
}

reg_results = []
trained_reg_models = {}

for name, model in reg_models.items():
    model.fit(X_train_reg_scaled, y_train_reg)
    y_pred = model.predict(X_test_reg_scaled)
    r2 = r2_score(y_test_reg, y_pred)

    trained_reg_models[name] = model
    reg_results.append({"Model": name, "R2 Score": r2})

reg_df = pd.DataFrame(reg_results).sort_values(by="R2 Score", ascending=False)
print("\nRegression Models Comparison:\n", reg_df.to_string(index=False))



--- Step 3: Training Regression Models ---

Regression Models Comparison:
                    Model  R2 Score
       Linear Regression  0.452603
           KNN Regressor  0.424809
Support Vector Regressor  0.182217
 Decision Tree Regressor  0.077603


In [7]:
# Q4. BEST MODEL SELECTION & SAVING

print("\n--- Step 4: Saving Best Models ---")

best_clf_name = clf_df.iloc[0]["Model"]
best_clf_model = trained_clf_models[best_clf_name]

best_reg_name = reg_df.iloc[0]["Model"]
best_reg_model = trained_reg_models[best_reg_name]

print(f"Best Classification Model: {best_clf_name}")
print(f"Best Regression Model: {best_reg_name}")

# Save Models to files
joblib.dump(best_clf_model, 'best_classification_model.pkl')
joblib.dump(scaler_clf, 'clf_scaler.pkl')
joblib.dump(list(X_clf.columns), 'clf_features.pkl')

joblib.dump(best_reg_model, 'best_regression_model.pkl')
joblib.dump(scaler_reg, 'reg_scaler.pkl')
joblib.dump(list(X_reg.columns), 'reg_features.pkl')

print("\nAll .pkl files generated successfully!")


--- Step 4: Saving Best Models ---
Best Classification Model: Support Vector Machine
Best Regression Model: Linear Regression

All .pkl files generated successfully!
